# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on: [workflow_dispatch]

jobs:
  e2e:
    runs-on: ubuntu-latest
    - run: echo "Run e2e"

  deployProd:
    runs-on: ubuntu-latest
    needs: e2e
    - run: echo "Deploy to prod"
